name: CI Guifaffinity Client

on: [push, pull_request]

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: client/npm test
